### ISSUE TITLE
有时觉得干 IT 的挺高端, 有时又觉得完全就是苦逼, 大家怎么看?

### ISSUE THREAD

**Issue by bigzhu** [yncoder/yncoder.github.io#45]
起因是这样的, 晚上陪客户喝酒, 叫了代驾, 和他吹了一路. 

他说他是部队转业的, 今年干蔬菜运输贩卖(到省外) , 亏了 60 多万了. 反正也没什么可干的, 就出来干干代驾. 

听完我好欣慰的, 近期创业和投资失败的钱也没他多, 他这心态多好啊, 我要学习....

然后他说, 以前好时一个月可以挣个十四万多,  单去年就挣了一百多么万了. 听完我整个人都不好了......

IT 这行当, 似乎在云南工资也不低了, 可是得看和什么比了. 不知大家怎么看?

抱歉了, 我又传播负能量了, 其实我是有意的, 不然社区 Issues 逼格太高了, 没人敢发贴的样...反正我脸皮厚, 就由我来拉低下吧.

顺便说下, 饭局间我那客户笑嘻嘻的和我说, 他股灾亏了 1000 多万在里面了.....然后呢, 他还欠我 1万的项目款没有付呢.  负能量到底, 反正我喝多了, 不用负责任.

**Comment by danielliao11** [comment]
技术工人和有产阶级的差别

**Comment by mytharcher** [comment]
你看，客户说亏钱了就是不想付钱给你的借口。另外为啥你打的都是半角标点，好不习惯。

**Comment by ttop5** [comment]
比上不足，比下有余 :expressionless:

**Comment by ghost** [comment]
我觉得，由于网上对程序员工作/加班的高曝光，导致了程序员群体对于自己的工作强度有了错误认识。

现在大部分的工作岗位，从工作强度和工作环境上来说，都比程序员要艰苦。

并且程序员本身还有 DRY 的基因在，随着经验的增长，工作只会越来越轻松。

相比其他工作的性价比已经很高了。

**Comment by ynzkai** [comment]
不排除有的人是习惯性装B...来自我的华为手机-------- 原始邮件 --------主题：[yncoder/yncoder.github.io] 有时觉得干 IT 的挺高端, 有时又觉得完全就是苦逼, 大家怎么看? (#45)发件人：bigzhu 收件人："yncoder/yncoder.github.io" 抄送：Subscribed 起因是这样的, 晚上陪客户喝酒, 叫了代驾, 和他吹了一路.
他说他是部队转业的, 今年干蔬菜运输贩卖(到省外) , 亏了 60 多万了. 反正也没什么可干的, 就出来干干代驾.
听完我好欣慰的, 近期创业和投资失败的钱也没他多, 他这心态多好啊, 我要学习....
然后他说, 以前好时一个月可以挣个十四万多,  单去年就挣了一百多么万了. 听完我整个人都不好了......
IT 这行当, 似乎在云南工资也不低了, 可是得看和什么比了. 不知大家怎么看?
抱歉了, 我又传播负能量了, 其实我是有意的, 不然社区 Issues 逼格太高了, 没人敢发贴的样...反正我脸皮厚, 就由我来拉低下吧.
顺便说下, 饭局间我那客户笑嘻嘻的和我说, 他股灾亏了 1000 多万在里面了.....然后呢, 他还欠我 1万的项目款没有付呢.  负能量到底, 反正我喝多了, 不用负责任.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yncoder/yncoder.github.io","title":"yncoder/yncoder.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yncoder/yncoder.github.io"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"有时觉得干 IT 的挺高端, 有时又觉得完全就是苦逼, 大家怎么看? (#45)"}],"action":{"name":"View Issue","url":"https://github.com/yncoder/yncoder.github.io/issues/45"}}}

**Comment by bigzhu** [comment]
@mytharcher 写注释时不用切换中英文, 写 markdown 时也不用切换. 习惯了.
