### ISSUE TITLE
天啊噜，我们一直在招聘，从未停过Python/Js

### ISSUE THREAD

**Issue by arlicle** [yncoder/yncoder.github.io#49]
# 关于律品

律品是成立在北京，目前团队在昆明。想通过互联网技术手段为全国的人提供法律服务。真正做到每一个老百姓都用得起的法律服务。我们已经拿到300万一轮 + 500万一轮的投资，目前产品面向老百姓、政府和律师服务。目前团队很小，只有两种人程序猿和法律人，有20多个人，但是只有5名技术，有很多的发展空间和学习的机会。目前产品已经面向用户测试和使用，需要更多的小伙伴加入进来一起完善和改进。我们虽然工作在昆明，但是提供北上广的薪酬待遇。（期权啥的扯太远了，我们直接先来点实际的。）

我是公司的创始合伙人，我做了将近10年的开发，PHP＋Python，自己写过开发框架。喜欢敲敲代码和跑步，自己觉得公司正站在革命一个行业的风口，当你每天看到自己的产品帮助了全国好几万人解决了他们的痛点，收到全国各地人的感谢，你会每天工作都很高兴。帮助每一个老百姓真正打得起官司。
## 公司福利

基础：
1. 五险一金
2. 午餐、晚餐
3. 水果、零食、茶点
4. 合作愉快了 慢慢的可以远程工作，边旅行边工作。我时不时就是这样的，忽然晚上买一个第二天去泰国的机票，然后第二天下午就在清迈过泼水节，骑着大象敲代码了。

硬件配备：MacBook Pro 或者 Imac ，想要几个27寸的显示器都可以

所有的一切，我们只想要让你干活干得更爽！如果你有更好的意见，也可以提出来大家一起改进。

技术要求：Python or Js，如果你Vue React写的很好也不错。我们希望你的能力越厉害越好。
## 薪资范围：

5K--30K（学徒工不在此范围）

工作时间不定期，因为我们是专注于一个项目做开发，不是接各种单子，整体没那么累。但是时不时需要配合法律人的要求进行调整，偶尔加班赶下东西还是有的，不赶东西的时候，不管你在家还是哪里耍着，按时把要做的事情做了就行。

我们希望你能够具有责任心，有极强的学习能力，喜欢运动，喜欢分享。

还有什么问题就跟我联系来问我吧;) QQ: 158336429 Email: arlicle(AT)gmail.com

**Comment by ynzkai** [comment]
赞来自我的华为手机-------- 原始邮件 --------主题：[yncoder/yncoder.github.io] 天啊噜，我们一直在招聘，从未停过Python/Js (#49)发件人：Ediso rao 收件人："yncoder/yncoder.github.io" 抄送：Subscribed 关于律品
律品是成立在北京，目前团队在昆明。想通过互联网技术手段为全国的人提供法律服务。真正做到每一个老百姓都用得起的法律服务。我们已经拿到300万一轮 + 500万一轮的投资，目前产品面向老百姓、政府和律师服务。目前团队很小，只有两种人程序猿和法律人，有20多个人，但是只有5名技术，有很多的发展空间和学习的机会。目前产品已经面向用户测试和使用，需要更多的小伙伴加入进来一起完善和改进。我们虽然工作在昆明，但是提供北上广的薪酬待遇。（期权啥的扯太远了，我们直接先来点实际的。）
我是公司的创始合伙人，我做了将近10年的开发，PHP＋Python，自己写过开发框架。喜欢敲敲代码和跑步，自己觉得公司正站在革命一个行业的风口，当你每天看到自己的产品帮助了全国好几万人解决了他们的痛点，收到全国各地人的感谢，你会每天工作都很高兴。帮助每一个老百姓真正打得起官司。
公司福利
基础：

五险一金
午餐、晚餐
水果、零食、茶点
合作愉快了 慢慢的可以远程工作，边旅行边工作。我时不时就是这样的，忽然晚上买一个第二天去泰国的机票，然后第二天下午就在清迈过泼水节，骑着大象敲代码了。

硬件配备：MacBook Pro 或者 Imac ，想要几个27寸的显示器都可以
所有的一切，我们只想要让你干活干得更爽！如果你有更好的意见，也可以提出来大家一起改进。
技术要求：Python or Js，如果你Vue React写的很好也不错。我们希望你的能力越厉害越好。
薪资范围：
5K--30K（学徒工不在此范围）
工作时间不定期，因为我们是专注于一个项目做开发，不是接各种单子，整体没那么累。但是时不时需要配合法律人的要求进行调整，偶尔加班赶下东西还是有的，不赶东西的时候，不管你在家还是哪里耍着，按时把要做的事情做了就行。
我们希望你能够具有责任心，有极强的学习能力，喜欢运动，喜欢分享。
还有什么问题就跟我联系来问我吧;) QQ: 158336429 Email: arlicle(AT)gmail.com

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yncoder/yncoder.github.io","title":"yncoder/yncoder.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yncoder/yncoder.github.io"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"天啊噜，我们一直在招聘，从未停过Python/Js (#49)"}],"action":{"name":"View Issue","url":"https://github.com/yncoder/yncoder.github.io/issues/49"}}}

**Comment by mdhh1988** [comment]
心水
